
// Copyright 2025 Henrik Steffen Gaßmann
//
// Distributed under the Boost Software License, Version 1.0.
//         (See accompanying file LICENSE or copy at
//           https://www.boost.org/LICENSE_1_0.txt)

#pragma once

// the configuration generated by cmake is fully optional
#if __has_include(<dplx/blake2/detail/config.hpp>)
#include <dplx/blake2/detail/config.hpp>
#endif

#if defined(_WIN32) || defined(__CYGWIN__)
#define DPLX_BLAKE2_DLL_IMPORT __declspec(dllimport)
#define DPLX_BLAKE2_DLL_EXPORT __declspec(dllexport)
#define DPLX_BLAKE2_DLL_PRIVATE
#elif __GNUC__ >= 4
#define DPLX_BLAKE2_DLL_IMPORT  __attribute__((visibility("default")))
#define DPLX_BLAKE2_DLL_EXPORT  __attribute__((visibility("default")))
#define DPLX_BLAKE2_DLL_PRIVATE __attribute__((visibility("hidden")))
#else
#define DPLX_BLAKE2_DLL_IMPORT
#define DPLX_BLAKE2_DLL_EXPORT
#define DPLX_BLAKE2_DLL_PRIVATE
#endif

#if defined(DPLX_BLAKE2_STATIC_DEFINE)
#define DPLX_BLAKE2_EXPORT
#define DPLX_BLAKE2_NO_EXPORT
#elif DPLX_BLAKE2_EXPORTS
#define DPLX_BLAKE2_EXPORT DPLX_BLAKE2_DLL_EXPORT
#define DPLX_BLAKE2_NO_EXPORT DPLX_BLAKE2_DLL_PRIVATE
#else
#define DPLX_BLAKE2_EXPORT DPLX_BLAKE2_DLL_IMPORT
#define DPLX_BLAKE2_NO_EXPORT DPLX_BLAKE2_DLL_PRIVATE
#endif
